logging:
    level:
        ROOT: INFO
        org.hibernate.SQL: ERROR
        org.hibernate: ERROR
        orh.springframework.web: ERROR
        com.zaxxer.hikari.HikariConfig: ERROR
        sne.chaka.demo: info
spring:
    profiles:
        active: prod
        include: 
    # DEVTOOLS PROPERTIES
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    output:
      ansi:
        enabled: always
    # DATASOURCE
    datasource:
        type: com.zaxxer.hikari.HikariDataSource 
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false 
        username: root   
        password:
    # JPA
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
        database: MYSQL
        generate-ddl: true
        show-sql: true
        properties: 
            hibernate.id.new_generator_mappings: true 
            hibernate.cache.use_second_level_cache: true 
            hibernate.cache.use_query_cache: false 
            hibernate.generate_statistics: false
    # H2 Web Console 
    h2:
        console:
            enabled: true
            path: /h2-console
# =================================================================== 
# Application specific properties 
# =================================================================== 
hello: 
    prefix : hello
    target: prod
    