spring:
    profiles:
        active: prod
        include: 
    # DEVTOOLS PROPERTIES
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    output:
      ansi:
        enabled: always
    # DATASOURCE
    datasource:
        url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: demo  
        password:
        driver-class-name: org.h2.Driver
    # JPA
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        generate-ddl: true
        show-sql: true
    # H2 Web Console 
    h2:
        console:
            enabled: true
            path: /h2-console
# =================================================================== 
# Application specific properties 
# =================================================================== 
hello: 
    prefix : hello
    target: prod